name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            call_gradle: gradlew
            call_sdk_manager: ${ANDROID_HOME}\tools\bin\sdkmanager 
          - os: ubuntu-latest
            call_gradle: ./gradlew
            call_sdk_manager: ${ANDROID_HOME}/tools/bin/sdkmanager 
          - os: macos-latest
            call_gradle: ./gradlew
            call_sdk_manager: ${ANDROID_HOME}/tools/bin/sdkmanager 
      fail-fast: false

    runs-on: ${{ matrix.os }}

  steps:
  - name: Install NDK
    run: ${{ matrix.call_sdk_manager }} "ndk;21.4.7075529"

  - name: Install CMake
    run: ${{ matrix.call_sdk_manager }} "cmake;3.18.1"

  - name: Gradle Build
    run: |
      cd HelloWorld
      ${{ matrix.call_gradle }} assemble 
