# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            call_gradle: gradlew
            call_sdk_manager: ${ANDROID_HOME}/tools/bin/sdkmanager 
          - os: ubuntu-latest
            call_gradle: ./gradlew
            call_sdk_manager: ${ANDROID_HOME}/tools/bin/sdkmanager 
          - os: macos-latest
            call_gradle: ./gradlew
            call_sdk_manager: ${ANDROID_HOME}/tools/bin/sdkmanager 
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install NDK
        run: ${{ matrix.call_sdk_manager }} "ndk;21.4.7075529"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
