name: Configure and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Install NDK
        run: ${ANDROID_HOME}/tools/bin/sdkmanager "ndk;21.4.7075529"
        
      - name: Install CMake
        run: ${ANDROID_HOME}/tools/bin/sdkmanager "cmake;3.18.1"

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
        
      - name: Build HelloWorld with Gradle
        run: |
          cd HelloWorld
          ./gradlew assemble
          
      - name: Upload Final Build State
        uses: actions/upload-artifact@v1
        with:
          name: final_state
          path: ./
        if: always()
